// swift-tools-version: 6.4
import CompilerPluginSupport
import PackageDescription

// WireMVC — a declarative-routing Wire adapter, proposal-native. Controllers written with
// `@Controller` / verb / param / response annotations have their route registration generated by
// the `@Controller` macro onto a `some RoutableHTTPServerBuilder`, which dispatches over the
// swift-http-api-proposal server (`HTTPServer.serve`) — so a controller serves on any concrete
// proposal server (e.g. swift-server's `NIOHTTPServer`) unchanged.
//
// `@Controller` aliases `@Contributes(to: RouteKeys.handlers)`, so swift-wire's graph collates the
// controllers; `Wire.bootstrap()` returns a graph conforming to `RouteComposable`, and `WireMVC.apply`
// registers the controllers onto a caller-owned `some RoutableHTTPServerBuilder` (a router, which is
// also the proposal's request handler, so it serves) — WireMVC stays router-agnostic. Depends on
// pushed swift-wire main; `WireMVCExample` is the runnable end-to-end validation, served on
// `NIOHTTPServer` via a concrete `WireRouter` that lives in the example.
//
// tools-version 6.4 and the experimental/upcoming-feature flags match the proposal stack — its API
// is compiled with them, so a consumer needs the same to call it. Requires a Swift 6.4 toolchain.
let proposalSettings: [SwiftSetting] = [
    .strictMemorySafety(),
    .enableExperimentalFeature("SuppressedAssociatedTypesWithDefaults"),
    .enableExperimentalFeature("LifetimeDependence"),
    .enableExperimentalFeature("Lifetimes"),
    .enableUpcomingFeature("LifetimeDependence"),
    .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
    .enableUpcomingFeature("InferIsolatedConformances"),
    .enableUpcomingFeature("ExistentialAny"),
    .enableUpcomingFeature("MemberImportVisibility"),
    .enableUpcomingFeature("InternalImportsByDefault"),
]

let package = Package(
    name: "wire-mvc",
    platforms: [.macOS(.v26)],
    products: [
        .library(name: "WireMVC", targets: ["WireMVC"]),
        .library(name: "WireMVCServerTransport", targets: ["WireMVCServerTransport"]),
    ],
    traits: [
        // Opt-in ServerTransport (swift-openapi-runtime) compatibility. Off by default, so the core
        // stays proposal-only and doesn't resolve OpenAPIRuntime; enable it to use the
        // `WireMVCServerTransport` adapter, which serves proposal-native WireMVC controllers on a
        // `some ServerTransport` (Hummingbird/Vapor via swift-openapi-hummingbird/-vapor).
        .trait(name: "ServerTransport")
    ],
    dependencies: [
        .package(url: "https://github.com/tachyonics/swift-wire.git", branch: "main"),
        .package(url: "https://github.com/apple/swift-http-api-proposal.git", .upToNextMinor(from: "0.2.0")),
        .package(
            url: "https://github.com/apple/swift-async-algorithms.git",
            exact: "1.1.5",
            traits: ["UnstableAsyncStreaming"]
        ),
        .package(url: "https://github.com/apple/swift-http-types.git", from: "1.6.0"),
        .package(url: "https://github.com/apple/swift-collections.git", from: "1.6.0"),
        .package(url: "https://github.com/swift-server/swift-http-server.git", branch: "main"),
        .package(url: "https://github.com/swift-server/swift-service-lifecycle.git", from: "2.0.0"),
        .package(url: "https://github.com/apple/swift-log.git", from: "1.13.2"),
        .package(url: "https://github.com/apple/swift-openapi-runtime.git", from: "1.7.0"),
        .package(url: "https://github.com/swiftlang/swift-syntax", branch: "release/6.4.x"),
    ],
    targets: [
        .macro(
            name: "WireMVCMacros",
            dependencies: [
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
                .product(name: "SwiftCompilerPlugin", package: "swift-syntax"),
            ]
        ),
        .target(
            name: "WireMVC",
            dependencies: [
                "WireMVCMacros",
                .product(name: "Wire", package: "swift-wire"),
                .product(name: "HTTPAPIs", package: "swift-http-api-proposal"),
                .product(name: "AsyncStreaming", package: "swift-async-algorithms"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
                .product(name: "BasicContainers", package: "swift-collections"),
                // The `services` collation key + `WireMVCComposable.services` surface app-scoped
                // `ServiceLifecycle` services the graph runs alongside the server.
                .product(name: "ServiceLifecycle", package: "swift-service-lifecycle"),
            ],
            swiftSettings: proposalSettings
        ),
        .executableTarget(
            name: "WireMVCExample",
            dependencies: [
                "WireMVC",
                .product(name: "Wire", package: "swift-wire"),
                .product(name: "HTTPAPIs", package: "swift-http-api-proposal"),
                .product(name: "AsyncStreaming", package: "swift-async-algorithms"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
                .product(name: "BasicContainers", package: "swift-collections"),
                .product(name: "NIOHTTPServer", package: "swift-http-server"),
                .product(name: "Logging", package: "swift-log"),
                // The generated `_WireGraph: WireMVCComposable` conformance references `any Service`.
                .product(name: "ServiceLifecycle", package: "swift-service-lifecycle"),
            ],
            swiftSettings: proposalSettings,
            plugins: [.plugin(name: "WireBuildPlugin", package: "swift-wire")]
        ),
        // Opt-in ServerTransport adapter — gated on the `ServerTransport` trait, so OpenAPIRuntime is
        // pruned from resolution unless a consumer enables it. Its sources are `#if ServerTransport`,
        // so the target compiles to an empty module when the trait is off.
        .target(
            name: "WireMVCServerTransport",
            dependencies: [
                "WireMVC",
                .product(name: "Wire", package: "swift-wire"),
                .product(name: "HTTPAPIs", package: "swift-http-api-proposal"),
                .product(name: "AsyncStreaming", package: "swift-async-algorithms"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
                .product(name: "BasicContainers", package: "swift-collections"),
                // `apply` returns the graph's collated `[any Service]`.
                .product(name: "ServiceLifecycle", package: "swift-service-lifecycle"),
                .product(
                    name: "OpenAPIRuntime",
                    package: "swift-openapi-runtime",
                    condition: .when(traits: ["ServerTransport"])
                ),
            ],
            swiftSettings: proposalSettings
        ),
        .testTarget(
            name: "WireMVCServerTransportTests",
            dependencies: [
                "WireMVCServerTransport",
                .product(name: "ServiceLifecycle", package: "swift-service-lifecycle"),
            ],
            swiftSettings: proposalSettings
        ),
    ]
)
