// swift-tools-version: 6.3
import CompilerPluginSupport
import PackageDescription

// WireMVC — a cross-runtime, declarative-routing Wire adapter. Controllers written with
// `@Controller` / verb / param / response annotations have their route registration
// generated by the `@Controller` macro onto `some ServerTransport` (the M3 collation
// surface), so a controller mounts on Hummingbird, Vapor, or Lambda unchanged.
//
// `@Controller` aliases `@Contributes(to: TransportKeys.handlers)`, so swift-wire's graph
// collates the controllers; `Wire.bootstrap()` returns a graph conforming to
// `TransportComposable`, which `WireMVC.apply` registers onto a user-owned transport.
// Depends on pushed swift-wire main; `WireMVCExample` is the runnable end-to-end validation.
let package = Package(
    name: "wire-mvc",
    platforms: [.macOS(.v15)],
    products: [
        .library(name: "WireMVC", targets: ["WireMVC"])
    ],
    dependencies: [
        .package(url: "https://github.com/tachyonics/swift-wire.git", branch: "main"),
        .package(url: "https://github.com/apple/swift-openapi-runtime.git", from: "1.7.0"),
        .package(url: "https://github.com/apple/swift-http-types.git", from: "1.0.0"),
        .package(url: "https://github.com/swiftlang/swift-syntax", "603.0.0"..<"604.0.0"),
    ],
    targets: [
        .macro(
            name: "WireMVCMacros",
            dependencies: [
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
                .product(name: "SwiftCompilerPlugin", package: "swift-syntax"),
            ]
        ),
        .target(
            name: "WireMVC",
            dependencies: [
                "WireMVCMacros",
                .product(name: "Wire", package: "swift-wire"),
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
            ]
        ),
        .executableTarget(
            name: "WireMVCExample",
            dependencies: [
                "WireMVC",
                .product(name: "Wire", package: "swift-wire"),
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
            ],
            plugins: [.plugin(name: "WireBuildPlugin", package: "swift-wire")]
        ),
    ]
)
