// swift-tools-version: 6.4
import CompilerPluginSupport
import PackageDescription

// WireMVC — a declarative-routing Wire adapter, proposal-native. Controllers written with
// `@Controller` / verb / param / response annotations have their route registration generated by
// the `@Controller` macro onto a `some RoutableHTTPServerBuilder`, which dispatches over the
// swift-http-api-proposal server (`HTTPServer.serve`) — so a controller serves on any concrete
// proposal server (e.g. swift-server's `NIOHTTPServer`) unchanged.
//
// `@Controller` aliases `@Contributes(to: RouteKeys.handlers)`, so swift-wire's graph collates the
// controllers; `Wire.bootstrap()` returns a graph conforming to `RouteComposable`, and `WireMVC.apply`
// registers the controllers onto a caller-owned `some RoutableHTTPServerBuilder` (a router, which is
// also the proposal's request handler, so it serves) — WireMVC stays router-agnostic. Depends on
// pushed swift-wire main; `WireMVCExample` is the runnable end-to-end validation, served on
// `NIOHTTPServer` via a concrete `WireRouter` that lives in the example.
//
// tools-version 6.4 and the experimental/upcoming-feature flags match the proposal stack — its API
// is compiled with them, so a consumer needs the same to call it. Requires a Swift 6.4 toolchain.
let proposalSettings: [SwiftSetting] = [
    .strictMemorySafety(),
    .enableExperimentalFeature("SuppressedAssociatedTypesWithDefaults"),
    .enableExperimentalFeature("LifetimeDependence"),
    .enableExperimentalFeature("Lifetimes"),
    .enableUpcomingFeature("LifetimeDependence"),
    .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
    .enableUpcomingFeature("InferIsolatedConformances"),
    .enableUpcomingFeature("ExistentialAny"),
    .enableUpcomingFeature("MemberImportVisibility"),
    .enableUpcomingFeature("InternalImportsByDefault"),
]

let package = Package(
    name: "wire-mvc",
    platforms: [.macOS(.v26)],
    products: [
        .library(name: "WireMVC", targets: ["WireMVC"])
    ],
    dependencies: [
        .package(url: "https://github.com/tachyonics/swift-wire.git", branch: "main"),
        .package(url: "https://github.com/apple/swift-http-api-proposal.git", .upToNextMinor(from: "0.2.0")),
        .package(
            url: "https://github.com/apple/swift-async-algorithms.git",
            exact: "1.1.5",
            traits: ["UnstableAsyncStreaming"]
        ),
        .package(url: "https://github.com/apple/swift-http-types.git", from: "1.6.0"),
        .package(url: "https://github.com/apple/swift-collections.git", from: "1.6.0"),
        .package(url: "https://github.com/swift-server/swift-http-server.git", branch: "main"),
        .package(url: "https://github.com/apple/swift-log.git", from: "1.13.2"),
        .package(url: "https://github.com/swiftlang/swift-syntax", branch: "release/6.4.x"),
    ],
    targets: [
        .macro(
            name: "WireMVCMacros",
            dependencies: [
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
                .product(name: "SwiftCompilerPlugin", package: "swift-syntax"),
            ]
        ),
        .target(
            name: "WireMVC",
            dependencies: [
                "WireMVCMacros",
                .product(name: "Wire", package: "swift-wire"),
                .product(name: "HTTPAPIs", package: "swift-http-api-proposal"),
                .product(name: "AsyncStreaming", package: "swift-async-algorithms"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
                .product(name: "BasicContainers", package: "swift-collections"),
            ],
            swiftSettings: proposalSettings
        ),
        .executableTarget(
            name: "WireMVCExample",
            dependencies: [
                "WireMVC",
                .product(name: "Wire", package: "swift-wire"),
                .product(name: "HTTPAPIs", package: "swift-http-api-proposal"),
                .product(name: "AsyncStreaming", package: "swift-async-algorithms"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
                .product(name: "BasicContainers", package: "swift-collections"),
                .product(name: "NIOHTTPServer", package: "swift-http-server"),
                .product(name: "Logging", package: "swift-log"),
            ],
            swiftSettings: proposalSettings,
            plugins: [.plugin(name: "WireBuildPlugin", package: "swift-wire")]
        ),
    ]
)
