import OpenAPIRuntime
import Wire

/// A transport contributor — its `registerWireHandlers` witness is generated by
/// `@Controller`, registering each of the controller's routes onto a `some ServerTransport`.
/// Not written by hand (the `Wire` in the name marks it generated).
///
/// `Sendable` because a controller is an app-scoped singleton whose route handlers run
/// concurrently per request.
///
/// > Note: self-contained for now (Option B). The final M5.1 task extracts this and the
/// > collation key into a shared package so WireMVC and WireOpenAPI fold into one surface.
public protocol TransportContributor: Sendable {
    func registerWireHandlers(on transport: any ServerTransport) throws
}

/// The collation keys namespace. Named for the cross-runtime surface (`Transport`), not the
/// package, so this and WireOpenAPI's controllers fold into the same key once the shared
/// surface is extracted (Option B).
public enum TransportKeys {}

extension TransportKeys {
    /// The key `@Controller` aliases into — the graph collates every controller here.
    public static let handlers = CollectedKey<any TransportContributor>()
}
