import OpenAPIRuntime

/// A transport contributor — its `registerWireHandlers` witness is generated by
/// `@Controller`, registering each of the controller's routes onto a `some ServerTransport`.
/// Not written by hand (the `Wire` in the name marks it generated).
///
/// `Sendable` because a controller is an app-scoped singleton whose route handlers run
/// concurrently per request.
///
/// > Note: self-contained for now (Option B). The final M5.1 task extracts this and the
/// > collation key into a shared package so WireMVC and WireOpenAPI fold into one surface.
public protocol TransportContributor: Sendable {
    func registerWireHandlers(on transport: any ServerTransport) throws
}
