import Testing
import WireMVCTesting

@testable import WireMVCBootstrapExample

// End-to-end proof of the generated `.wiremvc()` suite trait. `WireMVCBootstrapExample` is a real
// `@WireMVCBootstrap` app whose `@main` and `.wiremvc()` suite-trait factory are both generated by
// `WireMVCRouteGen`. `@Suite(.wiremvc())` bootstraps the graph, builds and wraps the router, and serves on
// an ephemeral loopback port once for the suite; each test reaches it through `TestClient.current` — proving
// the generated factory compiles AND the `WireMVCTesting` seam serves and drives requests end to end. The
// suite's tests are read-only `GET`s against a shared server (no mutable backend state), so it stays parallel.

@Suite(.wiremvc())
struct WithTestServerTests {
    /// `GET /hello/{name}` routes through the graph-constructed `HelloController` (its injected `Greeter`)
    /// and answers `{"message":"Hello, <name>!"}` — a real 200 over HTTP via the generated suite server.
    @Test func servesHelloRouteOverEphemeralPort() async throws {
        let client = TestClient.current
        let response = try await client.get("/hello/Alice")
        #expect(response.status == 200)
        let greeting = try response.json(Greeting.self)
        #expect(greeting.message == "Hello, Alice!")
    }

    /// `GET /hello/tenant` throws `TenantMissing`, which the composition root's global
    /// `@ErrorResponse(TenantMissing.self, .badRequest)` maps — proving the global tier serves over the seam.
    @Test func globalErrorTierMapsToBadRequest() async throws {
        let response = try await TestClient.current.get("/hello/tenant")
        #expect(response.status == 400)
    }

    /// An unmatched path hits the `@NotFound` `@RawRoute` fallback — a 404 with the handler's body.
    @Test func notFoundFallbackServes() async throws {
        let response = try await TestClient.current.get("/no/such/route")
        #expect(response.status == 404)
        #expect(response.bodyText.contains("no route here"))
    }
}
