import Testing
import WireMVCTesting

@testable import WireMVCBootstrapExample

// End-to-end proof of the generated `withTestServer` entry. `WireMVCBootstrapExample` is a real
// `@WireMVCBootstrap` app whose `@main` and `withTestServer` are both generated by `WireMVCRouteGen`.
// These tests call the generated `withTestServer { client in … }`, which bootstraps the graph, builds
// and wraps the router, serves on an ephemeral loopback port, and hands over a `TestClient` — proving
// the generated entry compiles AND the `WireMVCTesting` seam serves and drives requests end to end.

@Suite("Generated withTestServer entry")
struct WithTestServerTests {
    /// `GET /hello/{name}` routes through the graph-constructed `HelloController` (its injected `Greeter`)
    /// and answers `{"message":"Hello, <name>!"}` — a real 200 over HTTP via the generated entry.
    @Test func servesHelloRouteOverEphemeralPort() async throws {
        try await withTestServer { client in
            let response = try await client.get("/hello/Alice")
            #expect(response.status == 200)
            let greeting = try response.json(Greeting.self)
            #expect(greeting.message == "Hello, Alice!")
        }
    }

    /// `GET /hello/tenant` throws `TenantMissing`, which the composition root's global
    /// `@ErrorResponse(TenantMissing.self, .badRequest)` maps — proving the global tier serves over the seam.
    @Test func globalErrorTierMapsToBadRequest() async throws {
        try await withTestServer { client in
            let response = try await client.get("/hello/tenant")
            #expect(response.status == 400)
        }
    }

    /// An unmatched path hits the `@NotFound` `@RawRoute` fallback — a 404 with the handler's body.
    @Test func notFoundFallbackServes() async throws {
        try await withTestServer { client in
            let response = try await client.get("/no/such/route")
            #expect(response.status == 404)
            #expect(response.bodyText.contains("no route here"))
        }
    }
}
